environment: "uat"

data:
  input:
    database: "default"
    train_dataset: "train_iris_dataset"
    test_dataset: "test_iris_dataset"
    scored_inference_dataset: "scored_inference_dataset"  
    label_table: "label_table"  
  output:
    database: "default"
    data_monitoring: "data_monitoring" 
    performance_monitoring: "performance_monitoring"

model:
  model_name: "IrisClassificationRF"
  model_stage: "Staging"   
  experiment_name: "/Shared/simple-rf-sklearn_experiment"
  hyperparameters_grid:
    max_depth: [3, 10]
    n_estimators: [30, 50]
    max_features: ["auto"]
    criterion: ["gini", "entropy"]
  hyperparameters_fixed:
    class_weight: "balanced"
    bootstrap: "True"
    random_state: "21"
  minimal_threshold: 0.8