environment: "staging"

data:
  input:
    database: "default"
    test_dataset: "test_iris_dataset"
  output:
    database: "default"
    test_dataset: "test_iris_dataset"

model:
  model_name: "IrisClassificationRF"
  model_stage: "Staging"  
  experiment_name: "/Shared/simple-rf-sklearn_experiment"
  hyperparameters_grid:
    max_depth: [3, 10]
    n_estimators: [30, 50]
    max_features: ["auto"]
    criterion: ["gini", "entropy"]
  hyperparameters_fixed:
    class_weight: "balanced"
    bootstrap: "True"
    random_state: "21"
  minimal_threshold: 0.8